import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread('dragon.jpg', cv2.IMREAD_GRAYSCALE)
if img is None:
    print("Error: no se encontró la imagen")
    exit()
hist_original = cv2.calcHist([img], [0], None, [256], [0,256])
img_eq = cv2.equalizeHist(img)
hist_eq = cv2.calcHist([img_eq], [0], None, [256], [0,256])
plt.figure(figsize=(12,8))
plt.subplot(2,2,1)
plt.imshow(img, cmap='gray')
plt.title("Imagen Original (Bajo Contraste)")
plt.axis('off')
plt.subplot(2,2,2)
plt.plot(hist_original)
plt.title("Histograma Original")
plt.xlim([0,256])
plt.subplot(2,2,3)
plt.imshow(img_eq, cmap='gray')
plt.title("Imagen Ecualizada (Mejor Contraste)")
plt.axis('off')
plt.subplot(2,2,4)
plt.plot(hist_eq)
plt.title("Histograma Ecualizado")
plt.xlim([0,256])
plt.tight_layout()
plt.show()
cv2.imshow("Original", img)
cv2.imshow("Ecualizada", img_eq)
cv2.waitKey(0)
cv2.destroyAllWindows()
