import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread('mano.jpg', cv2.IMREAD_GRAYSCALE)
if img is None:
    print("Error: no se encontró la imagen")
    exit()
rows, cols = img.shape
M1 = np.float32([[1, 0, 50],
                 [0, 1, 30]])
traslacion1 = cv2.warpAffine(img, M1, (cols, rows))
M2 = np.float32([[1, 0, 20.5],
                 [0, 1, 15.5]])
traslacion2 = cv2.warpAffine(img, M2, (cols, rows))
centro = (cols // 2, rows // 2)
M_rot = cv2.getRotationMatrix2D(centro, 45, 1)
rotada = cv2.warpAffine(img, M_rot, (cols, rows))
escala_150 = cv2.resize(img, None, fx=1.5, fy=1.5, interpolation=cv2.INTER_LINEAR)
escala_50 = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_LINEAR)
plt.figure(figsize=(12,10))
plt.subplot(2,3,1)
plt.imshow(img, cmap='gray')
plt.title("Original")
plt.axis('off')
plt.subplot(2,3,2)
plt.imshow(traslacion1, cmap='gray')
plt.title("Traslación (50,30)")
plt.axis('off')
plt.subplot(2,3,3)
plt.imshow(traslacion2, cmap='gray')
plt.title("Traslación decimal")
plt.axis('off')
plt.subplot(2,3,4)
plt.imshow(rotada, cmap='gray')
plt.title("Rotación 45°")
plt.axis('off')
plt.tight_layout()
plt.show()
plt.figure(figsize=(15,5))
plt.subplot(1,3,1)
plt.imshow(img, cmap='gray')
plt.title(f"Original {img.shape}")
plt.axis('off')
plt.subplot(1,3,2)
plt.imshow(escala_150, cmap='gray')
plt.title(f"150% {escala_150.shape}")
plt.axis('off')
plt.subplot(1,3,3)
plt.imshow(escala_50, cmap='gray')
plt.title(f"50% {escala_50.shape}")
plt.axis('off')
plt.show()
cv2.imshow("Original", img)
cv2.imshow("Escala 150%", escala_150)
cv2.imshow("Escala 50%", escala_50)
cv2.waitKey(0)
cv2.destroyAllWindows()